# name: Listing and formatting check
# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

# jobs:
#   Continuous-Integration:
#     name: Perfors linting and formatting check
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Install Dependencies
#         run: npm install --legacy-peer-deps

#       - name: Run linters
#         run: npm run lint:check

#       - name: Check formatting
#         run: npm run format:fix
