name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.userApp
          push: true
          tags: harbinder04/harbinder-gogroceries:latest

      - name: Verify Pushed Image
        run: docker pull harbinder04/harbinder-gogroceries:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          KEY: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull harbinder/harbinder-gogroceries:latest
            sudo docker stop harbinder-gogroceries || true
            sudo docker rm harbinder-gogroceries || true
            sudo docker run -d --name harinder-gogroceries -p 3000:3000 harbinder04/harinder-gogroceries:latest
